#! bin/bash
# Preparation script for sniffing, must be logged in as root
read -p "You must be logged in as root. Press enter to run macchanger (wlan0, wlan0mon) and airmon for preparation..."
echo "Preppin' aint freshin'!"
sudo ifconfig wlan0 down
sudo macchanger -r wlan0
sudo ifconfig wlan0 up
sudo airmon-ng check kill
sudo airmon-ng start wlan0
sudo ifconfig wlan0mon down
sudo macchanger -r wlan0mon
sudo ifconfig wlan0mon up
echo "Done! You are now refreshed with wlan0 MAC spoofed!"
