#! bin/bash
# Preparation script for sniffing, must be logged in as root
echo "derp'n"
sudo ifconfig wlan0 down
sudo macchanger -r wlan0
sudo ifconfig wlan0 up
sudo ifconfig wlan0mon down
sudo macchanger -r wlan0mon
sudo ifconfig wlan0mon up
echo "Done. Spoofed on Wlan0"
